-- Audit log of manual decisions on a lead (overrides and the reasons given), and write attempts.

create table public.lead_events (
  id bigint generated by default as identity primary key,
  lead_id text not null references public.leads(id) on delete cascade,
  kind public.lead_event_kind not null,
  detail text not null,
  actor_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index lead_events_lead_id_idx on public.lead_events (lead_id);

alter table public.lead_events enable row level security;

create policy "lead_events_authenticated_all"
  on public.lead_events for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
