-- Do-not-contact list: an exact email address or a whole domain. Checked before any export row is
-- written; a match excludes the lead from the export.

create table public.suppression (
  id bigint generated by default as identity primary key,
  kind public.suppression_kind not null,
  -- Lowercased email address or bare domain (no @).
  value text not null unique,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.suppression enable row level security;

create policy "suppression_authenticated_all"
  on public.suppression for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
