-- Generated sequences. "generated by default as identity" (not "always") so the migration can insert
-- the exact original SQLite integer id, while new rows created by the app afterward still get one
-- assigned automatically.

create table public.lead_sequences (
  id bigint generated by default as identity primary key,
  lead_id text not null references public.leads(id) on delete cascade,
  tier public.lead_tier not null,
  status public.lead_sequence_status not null,
  sequence jsonb not null,
  -- Code validator result (issues list), and every writer draft with its own errors.
  validation jsonb not null,
  -- Judge verdict, or null when the judge did not run (the old template-only tier C sequences).
  judge jsonb,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create index lead_sequences_lead_id_idx on public.lead_sequences (lead_id);

alter table public.lead_sequences enable row level security;

create policy "lead_sequences_authenticated_all"
  on public.lead_sequences for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
