-- One row per Anthropic API call (successful or failed): the cost/token ledger the monthly spend cap
-- is computed from. lead_id uses "on delete set null" (not cascade): deleting a lead must never erase
-- money that was already spent researching or writing for it (see apps/server delete-lead.ts's SQLite
-- version of this same rule).
--
-- select + insert only, no update/delete policy (so those are simply denied): an append-only ledger,
-- same shape as the proposal-generator app's audit_log.

create table public.runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  model text not null,
  call_type public.run_call_type not null,
  lead_id text references public.leads(id) on delete set null,
  status public.run_status not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  cache_read_tokens integer not null default 0,
  cache_write_tokens integer not null default 0,
  cache_write_5m_tokens integer,
  cache_write_1h_tokens integer,
  prefix_key text,
  cost_usd numeric(10, 6) not null default 0,
  stop_reason text,
  message_id text,
  error text
);

create index runs_created_at_idx on public.runs (created_at);
create index runs_lead_id_idx on public.runs (lead_id);
create index runs_prefix_key_idx on public.runs (prefix_key);

alter table public.runs enable row level security;

create policy "runs_select_authenticated"
  on public.runs for select
  using (auth.uid() is not null);

create policy "runs_insert_authenticated"
  on public.runs for insert
  with check (auth.uid() is not null);
