/**
 * Research one lead and generate its sequence (Milestone 4), with the real API.
 *
 *   npm run write-sequence -- <url> [--refresh]
 *
 * Research reuses the page, robots.txt, and extraction caches (--refresh ignores them). Then the
 * sequence is generated by tier and gate: Tier C and gated leads make no writer or judge calls.
 * The full report (sequence, validator log, judge result, tokens, cost) is written to
 * data/reports/<lead>-sequence.txt; the console shows the summary block and the file path.
 */
import fs from "node:fs";
import path from "node:path";
import { isFound } from "@clearpath/shared";
import { and, eq, gt } from "drizzle-orm";
import { bootstrapOrExit } from "../src/bootstrap";
import { fromRoot } from "../src/config/paths";
import { leads, runs } from "../src/db/schema";
import { loadMxProviders, systemDnsResolver } from "../src/dns/lookup";
import { loadEvidence, loadOffer, loadScoring, loadStyle, loadWriterFacts } from "../src/docs/loader";
import { loadTemplates } from "../src/docs/templates";
import { loadExtractionSystemPrompt } from "../src/extract/prompt";
import { loadInjectionPatterns } from "../src/extract/untrusted";
import { HostRateLimiter } from "../src/fetch/rate-limit";
import { loadSkipPatterns } from "../src/fetch/select";
import { userAgentFor } from "../src/fetch/site";
import { systemResolver, undiciTransport } from "../src/fetch/transport";
import { lastRunId } from "../src/llm/client";
import { researchWebLead, type ResearchDeps } from "../src/pipeline/research";
import { contactPlan } from "../src/scoring/contact";
import { renderEmail } from "../src/validators/email";
import { generateSequence } from "../src/write/generate";
import { loadJudgeSystemPrompt, loadWriterSystemPrompt } from "../src/write/prompt";
import { buildWriterInput } from "../src/write/writer-input";

const args = process.argv.slice(2);
const refresh = args.includes("--refresh");
const url = args.find((a) => !a.startsWith("--"));
if (!url) {
  console.error("usage: npm run write-sequence -- <url> [--refresh]");
  process.exit(2);
}

const ctx = bootstrapOrExit();
const offer = loadOffer();
const facts = loadWriterFacts();
const evidence = loadEvidence();
const research: ResearchDeps = {
  db: ctx.db,
  llm: ctx.llm,
  modelExtract: ctx.env.MODEL_EXTRACT,
  systemPrompt: loadExtractionSystemPrompt(),
  caps: { perPage: ctx.env.MAX_TOKENS_PER_PAGE, perLead: ctx.env.MAX_INPUT_TOKENS_PER_LEAD },
  fetch: {
    resolver: systemResolver,
    transport: undiciTransport,
    userAgent: userAgentFor(ctx.env.CONTACT_URL),
    timeoutMs: ctx.env.FETCH_TIMEOUT_MS,
    maxBytes: ctx.env.FETCH_MAX_BYTES,
    skipPatterns: loadSkipPatterns(),
    limiter: new HostRateLimiter(1000),
  },
  dns: systemDnsResolver,
  mxProviders: loadMxProviders(),
  pageCacheDays: ctx.env.PAGE_CACHE_DAYS,
  injectionPatterns: loadInjectionPatterns(),
  scoring: loadScoring(),
  evidence,
  now: () => new Date(),
  refresh,
};

const site = url.replace(/^[a-z]+:\/\//i, "").split("/")[0]!.toLowerCase().replace(/^www\./, "").replace(/[^a-z0-9]+/g, "-");
const leadId = `live-${site}`;
const firstRunId = lastRunId(ctx.db);

console.error(`researching ${url} ...`);
const r = await researchWebLead(leadId, url, research);
const gateApproved = ctx.db.select({ v: leads.gateApproved }).from(leads).where(eq(leads.id, leadId)).get()?.v ?? false;
console.error(`generating sequence (tier ${r.score.tier}, gate ${r.dossier.gate.status}) ...`);
const g = await generateSequence(leadId, r.dossier, r.score.tier, {
  db: ctx.db,
  llm: ctx.llm,
  modelWrite: ctx.env.MODEL_WRITE,
  writerSystem: loadWriterSystemPrompt({ offer, facts }),
  judgeSystem: loadJudgeSystemPrompt({ offer, facts }),
  style: loadStyle(),
  offer,
  evidence,
  templates: loadTemplates(),
  facts,
}, { gateApproved });

// ---- report ----
const out: string[] = [];
const log = (s = "") => out.push(s);
const RULE = "=".repeat(90);
const usd = (n: number) => `$${n.toFixed(6)}`;
const d = r.dossier;
const plan = contactPlan(d);

log(RULE);
log(`LEAD ${leadId}   ${d.url}`);
log(`firm: ${isFound(d.firm_name) ? d.firm_name.value : "NOT_FOUND"}   type: ${isFound(d.firm_type) ? `${d.firm_type.value.primary}${d.firm_type.value.secondary.length ? ` (+${d.firm_type.value.secondary.join(", ")})` : ""}` : "NOT_FOUND"}`);
log(`gate: ${d.gate.status}${d.gate.reasons.length ? ` (${d.gate.reasons.join("; ")})` : ""}${gateApproved ? "   [gate approved by founder]" : ""}`);
log(`score: ${r.score.total}   tier: ${r.score.tier}${r.score.tierCapped ? " (capped at C by fit)" : ""}   research status: ${r.status}`);
if (d.declined_automated_access) log("ACCESS: the site declined automated access (HTTP 403/429). PASTE-TEXT PROMPT: paste the About/Team/Contact page text to research this lead fully.");
log(`greeting: ${JSON.stringify(plan.greeting)}   contact_mismatch: ${plan.contactMismatch}   generic_inbox: ${plan.genericInbox}   (${plan.reason})`);
log(RULE);
log("WRITER INPUT (values only; what the writer and judge see)");
const input = buildWriterInput(d, offer, evidence);
log(JSON.stringify(input.prospect_facts, null, 2));
if (input.filtered.length) log(`personal-detail filter removed: ${input.filtered.join("; ")}`);
log(RULE);
log(`SEQUENCE: ${g.status.toUpperCase()}   (${g.reason})`);
if (g.sequence) {
  log(`persona: ${g.sequence.persona}   angle: ${g.sequence.angle}`);
  for (const e of g.sequence.emails) {
    log("-".repeat(90));
    log(`EMAIL ${e.n}   day ${e.send_day}   ${e.template ? "TEMPLATE (docs/09)" : "CUSTOM (writer)"}   grounding: [${e.grounding.join(", ")}]`);
    if (e.subject_a) log(`subject A: ${e.subject_a}\nsubject B: ${e.subject_b}`);
    log("");
    log(renderEmail(e.body, offer));
  }
}
log(RULE);
log("VALIDATOR LOG (code)");
if (!g.validation) log("  (not run)");
else if (g.validation.issues.length === 0) log("  PASS, no issues");
else {
  log(`  ${g.validation.pass ? "PASS" : "FAIL"} (${g.validation.issues.filter((i) => i.severity === "error").length} errors, ${g.validation.issues.filter((i) => i.severity === "warning").length} warnings)`);
  for (const i of g.validation.issues) log(`  ${i.severity.toUpperCase()} ${i.email ? `email ${i.email}` : "sequence"} ${i.code}: ${i.message}`);
}
log("JUDGE");
if (!g.judge) log(`  not run (${g.writerCalls === 0 ? "no custom emails" : "writer failed"})`);
else if (g.judge.unsupported_claims.length === 0) log("  PASS: no unsupported claims");
else for (const c of g.judge.unsupported_claims) log(`  email ${c.email} ${c.reason}: ${JSON.stringify(c.claim)}`);
log(`approval: ${g.status === "passed" ? "allowed (sequence id " + g.sequenceId + ")" : "BLOCKED"}`);
log(RULE);
log("TOKENS AND COST (this command, this lead)");
const rows = ctx.db.select().from(runs).where(and(eq(runs.leadId, leadId), gt(runs.id, firstRunId))).all();
log("  call type        model                        input  output  cache read  cache write        cost");
for (const x of rows) {
  log(`  ${x.callType.padEnd(15)} ${x.model.padEnd(26)} ${String(x.inputTokens).padStart(7)} ${String(x.outputTokens).padStart(7)} ${String(x.cacheReadTokens).padStart(11)} ${String(x.cacheWriteTokens).padStart(12)} ${usd(x.costUsd).padStart(11)}${x.status === "error" ? `  ERROR ${x.error}` : ""}`);
}
if (rows.length === 0) log("  (no API calls: everything came from cache or no call was needed)");
const leadCost = rows.reduce((s, x) => s + x.costUsd, 0);
log(`  lead total ${usd(leadCost)}   month to date ${usd(ctx.gate.spentThisMonthUsd())} of $${ctx.gate.capUsd.toFixed(2)} cap`);

const dir = fromRoot("data/reports");
fs.mkdirSync(dir, { recursive: true });
const file = path.join(dir, `${site}-sequence.txt`);
fs.writeFileSync(file, out.join("\n") + "\n");

const errors = g.validation?.issues.filter((i) => i.severity === "error").length ?? 0;
const warnings = g.validation?.issues.filter((i) => i.severity === "warning").length ?? 0;
console.log(RULE);
console.log("SUMMARY");
console.log(`  ${leadId}: gate ${d.gate.status}, score ${r.score.total}, tier ${r.score.tier}${d.declined_automated_access ? ", DECLINED AUTOMATED ACCESS (paste text needed)" : ""}`);
console.log(`  sequence ${g.status} (${g.reason}); writer calls ${g.writerCalls}, judge calls ${g.judgeCalls}`);
console.log(`  validators: ${g.validation ? `${errors} errors, ${warnings} warnings` : "not run"}; judge: ${g.judge ? `${g.judge.unsupported_claims.length} unsupported claims` : "not run"}`);
console.log(`  cost this command ${usd(leadCost)} (${rows.map((x) => x.callType).join(", ") || "no API calls"}); month to date ${usd(ctx.gate.spentThisMonthUsd())} of $${ctx.gate.capUsd.toFixed(2)}`);
console.log(`  full report: ${file}`);
process.exit(0);
